Kybrnts.- 2018-02-06, New version release In update branch * Several corrections with button labels * Added form to allow user to select actions upon selected file * Added function to follow log file w/tail -F Changes requested for commit 	updated:    viewlogs

diff --git a/viewlogs b/viewlogs
--- a/viewlogs
+++ b/viewlogs
@@ -1,8 +1,8 @@
 #!/bin/sh
 #: Title        : Viewlogs
-#: Date         : 2018-01-15
+#: Date         : 2018-02-05
 #: Authors      : Written by: "Kybernetes" <correodelkybernetes@gmail.com>
-#: Version      : 1.1.0
+#: Version      : 1.2.0
 #: Description  : Executable Dash shell script file.
 #:              : Allows user to select and read a log file from a list of allowed directories.
 #: Installation : 01. Deploy script in /usr/local/bin/viewlogs
@@ -30,6 +30,7 @@ type stty >/dev/null || exit 1     ## Get current terminal information
 type file >/dev/null || exit 1     ## Get info about files to filter them
 type whiptail >/dev/null || exit 1 ## Display user-friendly dialog boxes
 type less >/dev/null || exit 1     ## Allow user to browse a given file's content
+type tail >/dev/null || exit 1     ## Allow user to follow a text file
 ##
 ## -- Globals ----------------------------------------------------------------------------------------------------------
 # Declare the following useful symbols:
@@ -215,7 +216,7 @@ _menu() { #@ DESCRIPTION: Displays a whiptail option menu using an array-like li
           #@              becomes a menu option and each index the corresponding option value. $1 is used as the menu
           #@              title, $2 as a suggestion text, $3 as the array basename $4 as the array length. After user
           #@              chooses an option, its value is written to above's global variable.
-          #@ USAGE: _menu TITLE SUGGESTION ARRAYBASENAME ARRAYSIZE
+          #@ USAGE: _menu TITLE SUGGESTION ARRAYBASENAME ARRAYSIZE [ OK_BUTTON_TEXT [ CANCEL_BUTTON_TEXT ] ]
           #@        DO NOT CALL DIRECTLY, use menu() wrapper instead.
     ## Local variables (If local is used, it should appear as the first statement of a function)
     local rws cls i tgitms itm
@@ -224,15 +225,16 @@ _menu() { #@ DESCRIPTION: Displays a whiptail option menu using an array-like li
         errmsg "Unable to get terminal size" ## Or finish w/errors
         return 1
     fi
-    i=0 tgitms=                              ## Initialize index and tags for each item in the menu list
-    while [ $i -lt $4 ]; do                  ## Get all array elements into an string of indexed tags
-        getvar itm $3_$i
+    i=0 tgitms=                              ## Initialize index and the taged list of items string
+    while [ $i -lt $4 ]; do                  ## Turn each array index into a menu tag followed by its matchig element's
+        getvar itm $3_$i                     ## double-quoted value, accumulating both into items string.
         tgitms=${tgitms:+"$tgitms "}"$i \"$itm\""
         i=$((i + 1))
     done                                     ## Now display the menu, and await for user's selection
-    _MSLCTD=$(eval "whiptail --title \"$1\" --menu \"$2\"\
-                       $((rws - 3)) $((cls - 30)) $((rws - 15))\
-                       $tgitms x Salir 3>&1 >&2 2>&3")
+    _MSLCTD=$(eval "whiptail --notags --title \"$1\" --menu \"$2\"\
+                             --ok-button \"${5:-OK}\" --cancel-button \"${6:-Cancel}\"\
+                             $((rws < 3 ? rws : rws - 3)) $((cls < 30 ? cls : cls - 30))\
+                             $((rws < 15 ? rws : rws - 15)) $tgitms x \"${6:-Cancel}\" 3>&1 >&2 2>&3")
     case $? in                               ## If an option is selected, then whiptail's exit status is 0. Else if
         0|1)                                 ## Cancel button is selected it will return 1.
             return $? ;;                     ##
@@ -242,32 +244,75 @@ _menu() { #@ DESCRIPTION: Displays a whiptail option menu using an array-like li
     esac
 }
 menu() { #@ DESCRIPTION: This is the wrapper for _menu(), that you generally want to use. In addition to wrapped's
-         #@              functionality, it stores the selected value in referenced name.
-         #@ USAGE: menu NAME TITLE SUGGESTION ARRAYNAME ARRAYSIZE
-    _menu ${2+"$2"} ${3+"$3"} ${4+"$4"} ${5+"$5"} || return $?
+         #@              functionality, it stores the selected item's value in referenced name.
+         #@ USAGE: menu NAME TITLE SUGGESTION ARRAYNAME ARRAYSIZE [ OK_BUTTON_TEXT [ CANCEL_BUTTON_TEXT ] ]
+    _menu ${2+"$2"} ${3+"$3"} ${4+"$4"} ${5+"$5"} ${6+"$6"} ${7+"$7"} || return $?
     setvar $1 "$_MSLCTD"
+}
+_RSLCTD=
+_radio() { #@ DESCRIPTION: Displays a whiptail radio list that allows user to select between actions to take upon the
+           #@               $1 path specified file.
+           #@ USAGE: _radio PATH
+           #@        DO NOT CALL DIRECTLY, use radio() wrapper instead.
+    ## Local variables (If local is used, it should appear as the first statement of a function)
+    local rws cls
+    rws=0 cls=0                              ## Initialize rows and columns values
+    if ! getTrmSze rws cls; then             ## Get current terminal size in above variables
+        errmsg "Unable to get terminal size" ## Or finish w/errors
+        return 1
+    fi                                       ## Now display the radio list awaiting for user to choose
+    _RSLCTD=$(whiptail --notags --title "Action select" --radiolist "Select action for $1:"\
+                       --ok-button OK --cancel-button Back\
+                       $((rws < 20 ? rws : 20)) $((cls < 60 ? cls : 60)) $((rws < 4 ? rws : 4))\
+                       1 "View   - less secure " on\
+                       2 "Follow - tail -F (rotation aware) " off\
+                       3 "Cancel - Go back " off 3>&1 >&2 2>&3)
+    case $? in                               ## If an option is selected, then whiptail's exit status is 0. Else if
+        0|1)                                 ## Cancel button is selected it will return 1.
+            return $? ;;                     ##
+        *)                                   ## In any other case, assume that something wen wrong w/whiptails's exec.
+            errmsg "Radio failed"
+            return 2 ;;
+    esac
+}
+radio() { #@ DESCRIPTION: This is the wrapper for _radio() that you generally want to use. In addition it stores the
+          #@              selected item value in $1 referenced name.
+          #@ USAGE: radio NAME PATH
+    _radio ${2+"$2"} || return $?
+    setvar $1 "$_RSLCTD"
 }
 istxtf() { #@ DESCRIPTION: Tests if $1 path is that of a plain/text file using "file" command. If it is, exit status
            #@ will be 0, otherwise it will be 1. A greater exit status indicates that file itself failed.
            #@ USAGE: istxtf PATH
     ## Local variables (If local is used, it should appear as the first statement of a function)
     local fout
-    fout=$(file -i "$1") || return 2
-    case $fout in
-        *text/plain*) return 0 ;;
+    fout=$(file -i "$1") || return 1               ## Get mime type string or fail
+    case $fout in                                  ## Test retreived mime type string
+        *inode/x-empty*)                           ## If this is an empty file fail w/specific exit status
+            errmsg "$1 is empty."                  ##
+            return 2 ;;                            ##
+        *text/plain*) return 0 ;;                  ## Else if this is a text file succeed..
+        *)                                         ## Fail in any other case w/generic status
+            errmsg "$1 is not a plain text file."
+            return 3 ;;
     esac
-    errmsg "$1 is not a plain text file."
-    return 1    
 }
-viewlog() { #@ DESCRIPTION: Allow user to safely browse $1 text file content.
+viewlog() { #@ DESCRIPTION: Allows user to safely browse $1 text file content.
             #@ USAGE: viewlog PATH
-    LESSSECURE=1 less "$1"
+    LESSSECURE=1 less "$1" ## Try to issue less in secure mode
+}
+fllwlog() { #@ DESCRIPTION: Allows user to follow (monitor) on $1 updates. It is also aware of file rotations. This
+            #@              makes it usefull when following for long periods.
+            #@ USAGE: fllwlog PATH
+    tail -F "$1"               ## Use tail's -F flag to report file rotations to STDOUT
+    [ $? -eq 130 ] && return 0 ## Tail seems to exit w/130 when Ctrl+C is issued by user (SIGTERM), hence normal exit
+    return 1                   ## Assume failure in any other case
 }
 ##
 ## -- Main -------------------------------------------------------------------------------------------------------------
 main() {
     ## Local variables (If local is used, it should appear as the first statement of a function)
-    local ldarr lds s_ld s_ldp lfarr lfs s_lf s_lfp
+    local ldarr lds s_ld s_ldp lfarr lfs s_lf s_lfp s_rd
     set -m -- ## Force job control ON and discard any positional parameters
     # Check for an interactive shell
     if [ ! -t 0 ]; then                      ## If current STDIN does NOT point to a terminal
@@ -285,7 +330,7 @@ main() {
     while :; do
         # Request user to select a directory from log directories array
         menu s_ld "Directory selection" "Select a log directory:" \
-                  ldarr $lds                             ## Display a menu using array elements as options
+                  ldarr $lds OK Exit                     ## Display a menu using array elements as options
         case $? in                                       ## Storing selected value in s_ld
             1) return 0 ;;                               ## Finish execution on "Cancel"
             2)                                           ## Also Finish execution w/errors when menu fails
@@ -307,12 +352,12 @@ main() {
                 while :; do
                     # Request user to select a log file to read
                     menu s_lf "Logfile selection" "Select a log file:" \
-                              lfarr $lfs                            ## Display menu using log files array as options
-                    case $? in                                      ## Sorting selected value in s_lf
-                        1)                                          ## Finish current loop on "Cancel" but make sure to
-                            unstArr $lfs lfarr                      ## destroy log files array before next iteration.
+                              lfarr $lfs OK Back                ## Display menu using log files array as options
+                    case $? in                                  ## Sorting selected value in s_lf
+                        1)                                      ## Finish current loop on "Cancel" but make sure to
+                            unstArr $lfs lfarr                  ## destroy log files array before next iteration.
                             break ;;
-                        2)                                          ## Finish execution w/errors when menu fails
+                        2)                                      ## Finish execution w/errors when menu fails
                             stdmsg "Unable to get answer from user"
                             sleep 3
                             return 5 ;;
@@ -324,13 +369,31 @@ main() {
                             break ;;
                         *)                                     ## Else..
                             getvar s_lfp lfarr_$s_lf           ## get selected array index value name in s_lfp
-                            s_lfp="$s_ldp/$s_lfp"              ## Pre-append container's path
-                            if ! istxtf "$s_lfp"; then
-                                stdmsg "File $s_lfp won't be shown"
-                                sleep 3
-                            elif ! viewlog "$s_lfp"; then      ## Try to browse selected log
-                                stdmsg "Unable to read $s_lfp" ## Or Display error message
-                                sleep 3                        ## Allowing some time to read output
+                            if ! istxtf "$s_ldp/$s_lfp"; then  ## Pre-append container's path and test if text file
+                                stdmsg "Could not select specified file"
+                                sleep 3                        ## Allow user to read why won't display non-text file
+                            else                               ## If this is a text file..
+                                radio s_rd "$s_lfp"            ## Allow user to choose what to do w/radio item list
+                                case $? in                     ## Storing selected item value in s_rd
+                                    1) continue ;;             ## Go to previous menu on "Back"
+                                    2)                         ## Finish execution on any other exit status (error)
+                                        stdmsg "Unable to get answer from user"
+                                        sleep 3
+                                        return 6 ;;
+                                esac
+                                # Take action according to user selected action
+                                case $s_rd in
+                                    1)                                     ## If user selected 1 (view w/less secure)
+                                        if ! viewlog "$s_ldp/$s_lfp"; then ## Try to use viewlog to page files's content
+                                            stdmsg "Unable to view $s_lfp" ## If above operation fails, display error
+                                            sleep 3                        ## Allow user to read above error
+                                        fi ;;                              ## Go back to file selection menu
+                                    2)                                       ## If user selected 2 (Follow file)
+                                        if ! fllwlog "$s_ldp/$s_lfp"; then   ## Try to use fllwlog to follow updates
+                                            stdmsg "Unable to follow $s_lfp" ## Or fail going back to file selection
+                                            sleep 3
+                                        fi ;;                              ## Go back to file selection menu in any
+                                esac                                       ## Other case
                             fi ;;
                     esac
                 done ;;
